### ISSUE TITLE
There is no parrots collection in the learnyoumongo

### ISSUE THREAD

**Issue by thanhacun** [evanlucas/learnyoumongo#10]
Challenge http://freecodecamp.com/challenges/waypoint-store-data-in-mongodb has an issue. Please describe how to reproduce it, and include links to screenshots if possible.

In lesson 3 of the learnyoumongo there is no parrots collection.

![image](https://cloud.githubusercontent.com/assets/7599781/9401185/adc718c6-47f5-11e5-8901-d4dcb20744ec.png)

**Comment by evanlucas** [comment]
The parrots collection is created when the exercise is verified and removed when the exercise is finished. I really need to add full `run` support where one could see what was actually inserted into the database though. Feel free to open a PR. Otherwise, I will get it done as soon as I can.

Thanks!
